variable "ENV" {}
variable "COMPONENT" {}
variable "SPOT_INSTANCE_TYPE" {}
variable "SPOT_INSTANCE_COUNT" {}
variable "OD_INSTANCE_COUNT" {}
variable "OD_INSTANCE_TYPE" {}
variable "APP_PORT" {}
variable "APP_VERSION" {}
variable "LB_TYPE" {}